[project]
name = "lark_bot"
version = "0.1.0"
description = "lark_bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "openai>=1.88.0",
    "redis>=6.2.0",
    "requests>=2.32.4",
    "python-dotenv>=1.0.0"
]
